<?php

return [
    'role_structure' => [
        'super_admin' => [
            'admin-user'                => 'i,c,r,u,d',
            'admin-role'                => 'i,c,r,u,d',
            'admin-permission'          => 'i,c,r,u,d',
            'admin-customer'            => 'i,c,r,u,d',
            'admin-seller-verification' => 'i,u',
            'admin-seller'              => 'i,c,r,u,d',
            'admin-article'             => 'i,c,r,u,d',
            'admin-site-testimony'      => 'i,c,r,u,d',
            'admin-faq'                 => 'i,c,r,u,d',
            'admin-complaint'           => 'i,c,r,u,d',
            'admin-promo'               => 'i,c,r,u,d',
            'admin-banner'              => 'i,c,r,u,d',
            'admin-slider'              => 'i,c,r,u,d',
            'admin-page'                => 'i,c,r,u,d',
            'admin-page-section'        => 'i,c,r,u,d',
            'admin-lead-sell'           => 'i,c,r,u,d',
            'admin-lead-tradein'        => 'i,c,r,u,d',
            'admin-lead-submitlist'     => 'i,c,r,u,d',
            'admin-car-brand'           => 'i,c,r,u,d',
            'admin-car-type'            => 'i,c,r,u,d',
            'admin-car-model'           => 'i,c,r,u,d',
            'admin-car-payment'         => 'i,c,r,u,d',
            'admin-unit'                => 'i,c,r,u,d',
            'admin-payment-method'      => 'i,c,r,u,d',
            'admin-leads-distribution'  => 'i,c,r,u,d',
            'admin-payment-duration'    => 'i,c,r,u,d',
            'admin-setting'             => 'i,c,r,u,d',
            'admin-service'             => 'i,c,r,u,d',
            'admin-sparepart'           => 'i,c,r,u,d',
            'admin-lead-transaction'    => 'i,c,r,u,d',
            'admin-ewallet'             => 'i,c,r,u,d',
            'admin-withdraw'            => 'i,c,r,u,d',
            'admin-service-payment'     => 'i,c,r,u,d',
            'admin-refund'              => 'i,c,r,u,d',
            'admin-disbursement'        => 'i,c,r,u,d',
            'admin-chat-history'        => 'i,r',
            'admin-order-complaint'     => 'i,c,r,u,d',
            'admin-forum-discussion'    => 'i,c,r,u,d',
            'admin-service-refund'      => 'i,c,r,u,d',
            'admin-payment-amount'      => 'i,c,r,u,d',
            'admin-tag'                 => 'i,c,r,u,d',
        ],
    ],
    'permissions_map' => [
        'i' => 'index',
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
    ],
];
