version: '3'

networks:
  proxy-network: {}
  internal-network: {}

services:
  service-admin:
    image: sumarsono/php:8.1-fpm-nodejs
    volumes:
      - ../:/var/www/html/service-admin
    networks:
      - proxy-network
      - internal-network
    env_file:
      - ../.env
    user: www-data:www-data
    networks:
      - proxy-network
      - internal-network

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./logs:/var/log/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../:/var/www/html/service-admin
    networks:
      - proxy-network
